name: Build BMI270 Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '4.5.1'
          fetch-depth: 0
          fetch-tags: true
      - name: Install correct ARM SDK
        run: make arm_sdk_install
      - name: Build
        run: |
          make TARGET=STM32F7X2 EXTRA_FLAGS="-DUSE_BARO_I2C_BMP388"
      - name: Upload hex
        uses: actions/upload-artifact@v4
        with:
          name: betaflight_4.5.1_STM32F7X2
          path: obj/*.hex
